MODEL:
  BACKBONE:
    NAME: resnet50
  PRETRAIN: imagenet

SAVE_DIR: output-resnet50-cub-softtriple

INPUT:
  MODE: 'RGB'
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

SOLVER:
  MAX_ITERS: 5000
  STEPS: [1200]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005

LOSSES:
  NAME: 'softtriple_loss'
  SOFTTRIPLE_LOSS:
    LA: 20
    GAMMA: 0.1
    TAU: 0.2
    MARGIN: 0.01
    K: 2
    CLUSTERS: 100

DATA:
  TRAIN_IMG_SOURCE: resource/datasets/CUB_200_2011/train.txt
  TEST_IMG_SOURCE: resource/datasets/CUB_200_2011/test.txt
  CLASS_COUNT_SOURCE: resource/datasets/CUB_200_2011/class_counts.json
  TRAIN_BATCHSIZE: 120
  TEST_BATCHSIZE: 128
  NUM_WORKERS: 8
  NUM_INSTANCES: 8

VALIDATION:
  VERBOSE: 200